POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego@rocketseat.com.br"
}

###

POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego@rocketseat.com.br",
  "referrer": "teste123"
}

###

GET http://localhost:3333/invites/teste123

###

GET http://localhost:3333/subscribers/teste123/ranking/clicks

###

GET http://localhost:3333/subscribers/teste123/ranking/count

###

GET http://localhost:3333/subscribers/teste123/ranking/position